use wasmtime::*;
use anyhow::Result;

/// AuraVM: A hyper-fast, perfectly isolated execution environment for AI agents.
pub struct AuraSandbox {
    engine: Engine,
}

impl AuraSandbox {
    /// Initializes the MicroVM Engine with strict security constraints.
    pub fn new() -> Result<Self> {
        let mut config = Config::new();
        
        // SECURITY FEATURE 1: Fuel Consumption.
        // Prevents the AI from writing "while(true) {}" and locking up our servers.
        // Every instruction executed costs "fuel". If it runs out, the VM kills the process.
        config.consume_fuel(true);

        // SECURITY FEATURE 2: Memory Isolation & Limits.
        // limits on RAM size to prevent Out-Of-Memory (OOM) attacks.
        // We will enforce the limits inside the Store during execution.

        let engine = Engine::new(&config)?;
        
        Ok(AuraSandbox { engine })
    }

    /// Executes a raw WebAssembly binary generated by an AI agent.
    /// This function boots the sandbox, executes the code, and destroys the sandbox in milliseconds.
    pub fn execute_agent_code(&self, wasm_bytes: &[u8], function_name: &str) -> Result<i32> {
        // 1. Compile the untrusted WebAssembly bytes into machine code
        let module = Module::from_binary(&self.engine, wasm_bytes)?;

        // Define strict limits: Maximum of 10 MB of memory per AI instance.
        // If the AI tries to allocate 11 MB, the VM instantly kills it.
        let limits = StoreLimitsBuilder::new()
            .memory_size(10 * 1024 * 1024) // 10 MB limit
            .instances(1) // Only allow 1 instance
            .build();

        // 2. Create a Store (The isolated execution environment) containing our limits
        let mut store = Store::new(&self.engine, limits);
        
        // Connect the StoreLimits to the store's resource limiter
        store.limiter(|state| state);

        // Give the AI exactly 10,000 instructions worth of "fuel" before it is forcefully terminated.
        store.set_fuel(10_000)?;

        // 3. Instantiate the module inside the sandbox
        let instance = Instance::new(&mut store, &module, &[])?;

        // 4. Extract the exported function the AI wants to run
        let func = instance.get_typed_func::<(), i32>(&mut store, function_name)?;

        // 5. Execute the code safely
        // If the code exceeds the fuel limit or crashes, this returns an Err() instead of crashing the host.
        let result = func.call(&mut store, ())?;

        // 6. The `store` and `instance` are dropped here, instantly destroying the MicroVM environment.
        Ok(result)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_secure_execution() {
        let sandbox = AuraSandbox::new().unwrap();

        // This is a pre-compiled WebAssembly binary (WAT format compiled to WASM).
        // It simply represents a function called "answer" that returns the integer 42.
        // (module
        //   (func (export "answer") (result i32)
        //     i32.const 42)
        // )
        let ai_generated_wasm = [
            0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // Magic + Version
            0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f,       // Type section
            0x03, 0x02, 0x01, 0x00,                         // Function section
            0x07, 0x0a, 0x01, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x00, 0x00, // Export section
            0x0a, 0x06, 0x01, 0x04, 0x00, 0x41, 0x2a, 0x0b  // Code section (returns 42)
        ];

        // Boot VM, execute, and destroy in under 5 milliseconds.
        let output = sandbox.execute_agent_code(&ai_generated_wasm, "answer").unwrap();
        
        assert_eq!(output, 42);
    }
}
