use wasmtime::*;
use wasmtime_wasi::p1::{WasiP1Ctx, add_to_linker_sync};
use wasmtime_wasi::WasiCtxBuilder;
use wasmtime_wasi::p2::pipe::MemoryOutputPipe;
use anyhow::Result;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub enum ExecutionStatus {
    Success,
    OutOfFuel,
    MemoryLimitExceeded,
    Trap(String),
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ExecutionReport {
    pub status: ExecutionStatus,
    pub exit_code: Option<i32>,
    pub fuel_consumed: Option<u64>,
    pub peak_memory: u64,
    pub stdout: String,
    pub stderr: String,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ExecutionLimits {
    pub fuel: Option<u64>,
    pub memory_limit_bytes: Option<u64>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum ValSnapshot {
    I32(i32),
    I64(i64),
    F32(u32),
    F64(u64),
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct VmSnapshot {
    pub memory_bytes: Vec<u8>,
    pub globals: std::collections::HashMap<String, ValSnapshot>,
}

pub struct StoreState {
    pub limits: StoreLimits,
    pub wasi: WasiP1Ctx,
    pub whitelisted_domains: Vec<String>,
}

/// AuraVM: A hyper-fast, perfectly isolated execution environment for AI agents.
pub struct AuraSandbox {
    engine: Engine,
}

impl AuraSandbox {
    /// Initializes the MicroVM Engine with strict security constraints.
    pub fn new() -> Result<Self> {
        let mut config = Config::new();
        
        // SECURITY FEATURE 1: Fuel Consumption.
        // Prevents the AI from writing "while(true) {}" and locking up our servers.
        // Every instruction executed costs "fuel". If it runs out, the VM kills the process.
        config.consume_fuel(true);

        // SECURITY FEATURE 2: Memory Isolation & Limits.
        // Limits on RAM size to prevent Out-Of-Memory (OOM) attacks.
        // Enforced inside the Store during execution.

        let engine = Engine::new(&config)?;
        
        Ok(AuraSandbox { engine })
    }

    /// Executes a raw WebAssembly binary generated by an AI agent.
    /// This function boots the sandbox, executes the code, captures telemetry, and destroys the sandbox in milliseconds.
    pub fn execute_agent_code(&self, wasm_bytes: &[u8], function_name: &str) -> Result<ExecutionReport> {
        self.execute_agent_code_with_limits(wasm_bytes, function_name, None, Vec::new())
    }

    /// Executes a raw WebAssembly binary with customized fuel, memory limits, and domain whitelist.
    pub fn execute_agent_code_with_limits(
        &self,
        wasm_bytes: &[u8],
        function_name: &str,
        limits: Option<ExecutionLimits>,
        whitelisted_domains: Vec<String>,
    ) -> Result<ExecutionReport> {
        // 1. Compile the untrusted WebAssembly bytes into machine code
        let module = Module::from_binary(&self.engine, wasm_bytes)?;

        let fuel_limit = limits.as_ref().and_then(|l| l.fuel).unwrap_or(10_000);
        let mem_limit = limits.as_ref().and_then(|l| l.memory_limit_bytes).unwrap_or(10 * 1024 * 1024);

        // Define strict limits: Maximum of 10 MB of memory per AI instance.
        let limits_struct = StoreLimitsBuilder::new()
            .memory_size(mem_limit as usize) // memory limit
            .instances(1) // Only allow 1 instance
            .build();

        // Create thread-safe in-memory pipes to capture stdout and stderr
        let stdout_pipe = MemoryOutputPipe::new(1024 * 1024);
        let stderr_pipe = MemoryOutputPipe::new(1024 * 1024);

        // Configure a secure WASI environment (Intercepts prints, denies file access)
        let mut wasi_builder = WasiCtxBuilder::new();
        wasi_builder.stdout(stdout_pipe.clone());
        wasi_builder.stderr(stderr_pipe.clone());
        let wasi = wasi_builder.build_p1();

        let state = StoreState { limits: limits_struct, wasi, whitelisted_domains };

        // 2. Create a Store containing our state
        let mut store = Store::new(&self.engine, state);
        
        // Connect the StoreLimits to the store's resource limiter
        store.limiter(|state| &mut state.limits);
        store.set_fuel(fuel_limit)?;

        // 3. Link WASI functions securely
        let mut linker = Linker::new(&self.engine);
        add_to_linker_sync(&mut linker, |state: &mut StoreState| &mut state.wasi)?;

        // Bind outbound HTTP whitelisted host proxy
        linker.func_wrap(
            "env",
            "host_http_get",
            |mut caller: Caller<'_, StoreState>, url_ptr: i32, url_len: i32, response_ptr: i32, response_max_len: i32| -> i32 {
                let mem = match caller.get_export("memory") {
                    Some(Extern::Memory(mem)) => mem,
                    _ => return -3, // Memory access error
                };
                let mut url_buf = vec![0u8; url_len as usize];
                if mem.read(&caller, url_ptr as usize, &mut url_buf).is_err() {
                    return -3;
                }
                let url_str = match std::str::from_utf8(&url_buf) {
                    Ok(s) => s,
                    Err(_) => return -4, // Invalid UTF-8
                };
                let parsed_url = match reqwest::Url::parse(url_str) {
                    Ok(u) => u,
                    Err(_) => return -5, // Invalid URL
                };
                let host = match parsed_url.host_str() {
                    Some(h) => h,
                    None => return -6, // Missing host
                };
                
                let is_whitelisted = caller.data().whitelisted_domains.iter().any(|domain| {
                    host == domain || host.ends_with(&format!(".{}", domain))
                });
                
                if !is_whitelisted {
                    return -1; // Blocked
                }
                
                let client = match reqwest::blocking::Client::builder()
                    .timeout(std::time::Duration::from_secs(5))
                    .build() {
                    Ok(c) => c,
                    Err(_) => return -2, // Client build failed
                };
                
                let response = match client.get(url_str).send() {
                    Ok(res) => res,
                    Err(_) => return -2, // HTTP request failed
                };
                
                let body_bytes = match response.bytes() {
                    Ok(b) => b,
                    Err(_) => return -2, // Bytes extraction failed
                };
                
                let write_len = std::cmp::min(body_bytes.len(), response_max_len as usize);
                if mem.write(&mut caller, response_ptr as usize, &body_bytes[..write_len]).is_err() {
                    return -3;
                }
                
                write_len as i32
            },
        )?;

        // 4. Instantiate the module inside the sandbox
        let instance = linker.instantiate(&mut store, &module)?;

        // 5. Extract the exported function the AI wants to run
        let func = instance.get_typed_func::<(), i32>(&mut store, function_name)?;

        // 6. Execute the code safely
        let mut execution_status = ExecutionStatus::Success;
        let mut exit_code = None;

        match func.call(&mut store, ()) {
            Ok(code) => {
                exit_code = Some(code);
            }
            Err(e) => {
                if let Some(trap) = e.downcast_ref::<Trap>() {
                    match trap {
                        Trap::OutOfFuel => {
                            execution_status = ExecutionStatus::OutOfFuel;
                        }
                        Trap::MemoryOutOfBounds => {
                            execution_status = ExecutionStatus::MemoryLimitExceeded;
                        }
                        other => {
                            execution_status = ExecutionStatus::Trap(format!("{:?}", other));
                        }
                    }
                } else if e.to_string().contains("resource limit exceeded") {
                    execution_status = ExecutionStatus::MemoryLimitExceeded;
                } else {
                    execution_status = ExecutionStatus::Trap(e.to_string());
                }
            }
        }

        // Get fuel consumed
        let fuel_consumed = if execution_status == ExecutionStatus::OutOfFuel {
            Some(fuel_limit)
        } else {
            store.get_fuel().ok().map(|remaining| fuel_limit - remaining)
        };

        // Get peak memory size
        let peak_memory = instance.get_memory(&mut store, "memory")
            .map(|mem| mem.data_size(&store) as u64)
            .unwrap_or(0);

        // 7. Drop the store and instance to release all references
        drop(store);

        // 8. Extract the captured stdout and stderr buffers
        let stdout = String::from_utf8_lossy(&stdout_pipe.contents()).into_owned();
        let stderr = String::from_utf8_lossy(&stderr_pipe.contents()).into_owned();

        Ok(ExecutionReport {
            status: execution_status,
            exit_code,
            fuel_consumed,
            peak_memory,
            stdout,
            stderr,
        })
    }

    /// Exposes an entrypoint that runs raw Javascript code strings inside the sandboxed QuickJS virtual machine.
    pub fn execute_js(&self, js_code: &str) -> Result<ExecutionReport> {
        let qjs_wasm = include_bytes!("../quickjs.wasm");

        // QuickJS engine takes slightly more memory. Give it 16MB.
        let limits = StoreLimitsBuilder::new()
            .memory_size(16 * 1024 * 1024)
            .instances(1)
            .build();

        let stdout_pipe = MemoryOutputPipe::new(1024 * 1024);
        let stderr_pipe = MemoryOutputPipe::new(1024 * 1024);

        let mut wasi_builder = WasiCtxBuilder::new();
        wasi_builder.stdout(stdout_pipe.clone());
        wasi_builder.stderr(stderr_pipe.clone());
        wasi_builder.args(&["qjs", "-e", js_code]);
        let wasi = wasi_builder.build_p1();

        let state = StoreState { limits, wasi, whitelisted_domains: Vec::new() };

        let mut store = Store::new(&self.engine, state);
        store.limiter(|state| &mut state.limits);
        store.set_fuel(100_000)?; // Allow more fuel for JS parsing

        let mut linker = Linker::new(&self.engine);
        add_to_linker_sync(&mut linker, |state: &mut StoreState| &mut state.wasi)?;

        let module = Module::from_binary(&self.engine, qjs_wasm)?;
        let instance = linker.instantiate(&mut store, &module)?;

        let func = instance.get_typed_func::<(), ()>(&mut store, "_start")?;

        let mut execution_status = ExecutionStatus::Success;

        match func.call(&mut store, ()) {
            Ok(()) => {}
            Err(e) => {
                if let Some(trap) = e.downcast_ref::<Trap>() {
                    match trap {
                        Trap::OutOfFuel => {
                            execution_status = ExecutionStatus::OutOfFuel;
                        }
                        Trap::MemoryOutOfBounds => {
                            execution_status = ExecutionStatus::MemoryLimitExceeded;
                        }
                        other => {
                            execution_status = ExecutionStatus::Trap(format!("{:?}", other));
                        }
                    }
                } else if e.to_string().contains("resource limit exceeded") {
                    execution_status = ExecutionStatus::MemoryLimitExceeded;
                } else {
                    // Handle normal exit (exit code 0 = success, non-zero = error)
                    let msg = e.to_string();
                    if msg.contains("exit with code 0") {
                        // Normal exit, keep Success status
                    } else {
                        execution_status = ExecutionStatus::Trap(msg);
                    }
                }
            }
        }

        let fuel_consumed = if execution_status == ExecutionStatus::OutOfFuel {
            Some(100_000)
        } else {
            store.get_fuel().ok().map(|remaining| 100_000 - remaining)
        };

        let peak_memory = instance.get_memory(&mut store, "memory")
            .map(|mem| mem.data_size(&store) as u64)
            .unwrap_or(0);

        drop(store);

        let stdout = String::from_utf8_lossy(&stdout_pipe.contents()).into_owned();
        let stderr = String::from_utf8_lossy(&stderr_pipe.contents()).into_owned();

        Ok(ExecutionReport {
            status: execution_status,
            exit_code: None,
            fuel_consumed,
            peak_memory,
            stdout,
            stderr,
        })
    }

    /// Captures the memory state and global variables of an active VM instance.
    pub fn take_snapshot(&self, store: &mut impl AsContextMut<Data = StoreState>, instance: &Instance) -> Result<VmSnapshot> {
        let mut memory_bytes = Vec::new();
        if let Some(memory) = instance.get_memory(&mut *store, "memory") {
            memory_bytes = memory.data(&*store).to_vec();
        }

        // Collect (name, Global) pairs first to avoid a double-mutable-borrow inside the for loop.
        let global_exports: Vec<(String, Global)> = instance
            .exports(&mut *store)
            .filter_map(|export| {
                let name = export.name().to_string();
                if let Extern::Global(global) = export.into_extern() {
                    Some((name, global))
                } else {
                    None
                }
            })
            .collect();

        let mut globals = std::collections::HashMap::new();
        for (name, global) in global_exports {
            let val = global.get(&mut *store);
            let snapshot_val = match val {
                Val::I32(i) => ValSnapshot::I32(i),
                Val::I64(i) => ValSnapshot::I64(i),
                Val::F32(f) => ValSnapshot::F32(f),
                Val::F64(f) => ValSnapshot::F64(f),
                _ => continue,
            };
            globals.insert(name, snapshot_val);
        }

        Ok(VmSnapshot { memory_bytes, globals })
    }

    /// Restores the memory state and global variables to a running instance.
    pub fn restore_snapshot(
        &self,
        mut store: impl AsContextMut<Data = StoreState>,
        instance: &Instance,
        snapshot: &VmSnapshot,
    ) -> Result<()> {
        if let Some(memory) = instance.get_memory(&mut store, "memory") {
            let write_len = std::cmp::min(memory.data_size(&store), snapshot.memory_bytes.len());
            memory.write(&mut store, 0, &snapshot.memory_bytes[..write_len])?;
        }

        for (name, val) in &snapshot.globals {
            if let Some(export) = instance.get_export(&mut store, name) {
                if let Extern::Global(global) = export {
                    let val = match *val {
                        ValSnapshot::I32(i) => Val::I32(i),
                        ValSnapshot::I64(i) => Val::I64(i),
                        ValSnapshot::F32(f) => Val::F32(f),
                        ValSnapshot::F64(f) => Val::F64(f),
                    };
                    global.set(&mut store, val)?;
                }
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_secure_execution_success() {
        let sandbox = AuraSandbox::new().unwrap();

        // WAT: Returns 42.
        let ai_generated_wasm = [
            0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
            0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f,
            0x03, 0x02, 0x01, 0x00,
            0x07, 0x0a, 0x01, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x00, 0x00,
            0x0a, 0x06, 0x01, 0x04, 0x00, 0x41, 0x2a, 0x0b
        ];

        let report = sandbox.execute_agent_code(&ai_generated_wasm, "answer").unwrap();
        
        assert_eq!(report.status, ExecutionStatus::Success);
        assert_eq!(report.exit_code, Some(42));
        assert!(report.fuel_consumed.unwrap() > 0);
    }

    #[test]
    fn test_infinite_loop_fuel_exhaustion() {
        let sandbox = AuraSandbox::new().unwrap();

        // WAT: An infinite loop function called "looping".
        // (module
        //   (func (export "looping") (result i32)
        //     (loop
        //       (br 0))
        //     (i32.const 0))
        // )
        let loop_wasm = [
            0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
            0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f,
            0x03, 0x02, 0x01, 0x00,
            0x07, 0x0b, 0x01, 0x07, 0x6c, 0x6f, 0x6f, 0x70, 0x69, 0x6e, 0x67, 0x00, 0x00,
            0x0a, 0x0b, 0x01, 0x09, 0x00, 0x03, 0x40, 0x0c, 0x00, 0x0b, 0x41, 0x00, 0x0b
        ];

        let report = sandbox.execute_agent_code(&loop_wasm, "looping").unwrap();
        
        assert_eq!(report.status, ExecutionStatus::OutOfFuel);
        assert_eq!(report.exit_code, None);
        assert_eq!(report.fuel_consumed, Some(10_000));
    }

    #[test]
    fn test_execute_js() {
        let sandbox = AuraSandbox::new().unwrap();
        let report = sandbox.execute_js("console.log('Hello from JS: ' + (2 + 2));").unwrap();
        assert_eq!(report.status, ExecutionStatus::Success);
        assert!(report.stdout.contains("Hello from JS: 4"));
    }

    #[test]
    fn test_snapshot_resumption() {
        let sandbox = AuraSandbox::new().unwrap();

        // A simple mutable global counter module.
        // NOTE: $counter must be exported so take_snapshot can find it via instance.exports().
        let counter_wat = r#"
            (module
              (global $counter (mut i32) (i32.const 0))
              (export "counter" (global $counter))
              (func (export "increment") (result i32)
                global.get $counter
                i32.const 1
                i32.add
                global.set $counter
                global.get $counter
              )
            )
        "#;
        let counter_wasm = wat::parse_str(counter_wat).unwrap();

        let module = Module::from_binary(&sandbox.engine, &counter_wasm).unwrap();
        let limits = StoreLimitsBuilder::new().memory_size(1024 * 1024).instances(1).build();
        let wasi = WasiCtxBuilder::new().build_p1();
        let state = StoreState { limits, wasi, whitelisted_domains: Vec::new() };
        let mut store = Store::new(&sandbox.engine, state);
        store.limiter(|state| &mut state.limits);
        store.set_fuel(1_000_000).unwrap(); // Plenty of fuel for counter calls
        let mut linker = Linker::new(&sandbox.engine);
        add_to_linker_sync(&mut linker, |s: &mut StoreState| &mut s.wasi).unwrap();
        let instance = linker.instantiate(&mut store, &module).unwrap();

        let increment = instance.get_typed_func::<(), i32>(&mut store, "increment").unwrap();

        // Increment once: should return 1
        let val1 = increment.call(&mut store, ()).unwrap();
        assert_eq!(val1, 1);

        // Take snapshot
        let snapshot = sandbox.take_snapshot(&mut store, &instance).unwrap();

        // Increment again on same instance: should return 2
        let val2 = increment.call(&mut store, ()).unwrap();
        assert_eq!(val2, 2);

        // Restore snapshot on a fresh instance/store
        let state2 = StoreState {
            limits: StoreLimitsBuilder::new().memory_size(1024 * 1024).instances(1).build(),
            wasi: WasiCtxBuilder::new().build_p1(),
            whitelisted_domains: Vec::new(),
        };
        let mut store2 = Store::new(&sandbox.engine, state2);
        store2.limiter(|state| &mut state.limits);
        store2.set_fuel(1_000_000).unwrap();
        let instance2 = linker.instantiate(&mut store2, &module).unwrap();

        sandbox.restore_snapshot(&mut store2, &instance2, &snapshot).unwrap();

        // Call increment on restored instance: should return 2 (restored state was 1, so 1 + 1 = 2)
        let restored_increment = instance2.get_typed_func::<(), i32>(&mut store2, "increment").unwrap();
        let val_restored = restored_increment.call(&mut store2, ()).unwrap();
        assert_eq!(val_restored, 2);
    }

    #[test]
    fn test_whitelisted_http() {
        let sandbox = AuraSandbox::new().unwrap();
        
        let wat_code = r#"
            (module
              (import "env" "host_http_get" (func $host_http_get (param i32 i32 i32 i32) (result i32)))
              (memory (export "memory") 1)
              (data (i32.const 0) "https://httpbin.org/get")
              (func (export "test_get") (result i32)
                (call $host_http_get (i32.const 0) (i32.const 23) (i32.const 100) (i32.const 500)))
            )
        "#;
        
        let wasm_bytes = wat::parse_str(wat_code).unwrap();
        
        // 1. Domain not whitelisted: should be blocked and return -1
        let report_blocked = sandbox.execute_agent_code_with_limits(
            &wasm_bytes,
            "test_get",
            None,
            vec!["google.com".to_string()], // Whitelist google.com, not httpbin.org
        ).unwrap();
        
        assert_eq!(report_blocked.status, ExecutionStatus::Success);
        assert_eq!(report_blocked.exit_code, Some(-1)); // -1 represents blocked
        
        // 2. Domain whitelisted: should succeed and write HTTP response body to memory
        let report_success = sandbox.execute_agent_code_with_limits(
            &wasm_bytes,
            "test_get",
            None,
            vec!["httpbin.org".to_string()], // Whitelist httpbin.org
        ).unwrap();
        
        assert_eq!(report_success.status, ExecutionStatus::Success);
        assert!(report_success.exit_code.unwrap() > 0); // Returns bytes written (>0)
    }
}
